server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
            - id: category-service
              uri: lb://category-service
              predicates:
                - Path=/categories/**
            - id: wallet-service
              uri: lb://wallet-service
              predicates:
                - Path=/wallets/**
            - id: transaction-service
              uri: lb://transaction-service
              predicates:
                - Path=/transactions/**
            - id: report-service
              uri: lb://report-service
              predicates:
                - Path=/reports/**