server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monio_category
    username: admin
    password: 171104
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true